/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutScreen: typeof import('./src/components/AboutScreen.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CommitDetail: typeof import('./src/components/CommitDetail.vue')['default']
    CommitsScreen: typeof import('./src/components/CommitsScreen.vue')['default']
    ConfigScreen: typeof import('./src/components/ConfigScreen.vue')['default']
    DataScreen: typeof import('./src/components/DataScreen.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    GraphsScreen: typeof import('./src/components/GraphsScreen.vue')['default']
    HomeScreen: typeof import('./src/components/HomeScreen.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MergeIcon: typeof import('./src/components/MergeIcon.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectSampleProject: typeof import('./src/components/SelectSampleProject.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    UploadDragAndDrop: typeof import('./src/components/UploadDragAndDrop.vue')['default']
    UploadInstructions: typeof import('./src/components/UploadInstructions.vue')['default']
  }
}
